# vi: sw=2 ts=2 sts=2 expandtab

parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # R3.14.12:
      #   VERSION_FILE: 'R3_14_12.sh'
      #   EPICS_HOST_ARCH: ${{ parameters.epics_host_arch }}
      R3.15:
        VERSION_FILE: 'R3_15.sh'
        EPICS_HOST_ARCH: ${{ parameters.epics_host_arch }}
      # R3.16:
      #   VERSION_FILE: 'R3_16.sh'
      #   EPICS_HOST_ARCH: ${{ parameters.epics_host_arch }}
      R7.0:
        VERSION_FILE: 'R7_0.sh'
        EPICS_HOST_ARCH: ${{ parameters.epics_host_arch }}
    maxParallel: 4

  steps:
  - bash: |
      env |grep "Visual Studio"
    displayName: 'VS Environment'

  - powershell: |
      $epics_base="C:\projects\epics-base-3.15\"
      $release_path="$epics_base\configure\RELEASE"
      $TOOLCHAIN="2017"
      $CONFIGURATION="STATIC"
      $PLATFORM="x64"
      if (!(Test-Path -Path $release_path)) {
        git clone --single-branch --branch=3.15 --depth=2 https://github.com/epics-base/epics-base $epics_base
        Push-Location $epics_base
        ci/appveyor-prepare.bat
        ci/appveyor-make.bat
        Pop-Location
      }
    displayName: 'Build'
